development:
  adapter: postgresql
  encoding: unicode
  database: document_plagiarism_detection_development
  pool: 5
  min_messages: warning
test:
  adapter: postgresql
  encoding: unicode
  database: document_plagiarism_detection_test<%= ENV['TEST_ENV_NUMBER'] %>
  # database: document_plagiarism_detection_test
  pool: 5
  min_messages: warning
production:
  adapter: postgresql
  encoding: unicode
  database: document_plagiarism_detection
  pool: 5
  min_messages: warning
